version: "3"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: dikadika007
      POSTGRES_USER: JD07
      POSTGRES_DB: test
    ports:
      - '5432:5432'
#  app:
#    image: book-api
#    ports:
#      - '3000:3000'

